FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY models/ /app/models/
COPY ml/ /app/ml/

EXPOSE 8000

CMD ["uvicorn", "ml.api:app", "--host", "0.0.0.0", "--port", "8000"]
