import Card from "../ui/Card";
import {
  BrainCircuit,
  ShieldCheck,
  AlertTriangle,
  Sparkles,
} from "lucide-react";

import { aiInsights } from "../../data/dashboardData";

const icons = [
  <BrainCircuit size={22} className="text-cyan-600" />,
  <ShieldCheck size={22} className="text-emerald-600" />,
  <AlertTriangle size={22} className="text-orange-500" />,
];

function AIRecommendations() {
  return (
    <Card className="h-full">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-semibold">
            AI Recommendations
          </h2>

          <p className="text-sm text-slate-500">
            Personalized insights generated by SmartAQI AI.
          </p>
        </div>

        <Sparkles className="text-cyan-600" size={28} />
      </div>

      <div className="space-y-4">
        {aiInsights.map((item, index) => (
          <div
            key={index}
            className="
              flex
              gap-4
              rounded-2xl
              border
              border-slate-200
              p-4
              hover:border-cyan-400
              hover:shadow-lg
              transition-all
              duration-300
            "
          >
            <div className="mt-1">
              {icons[index % icons.length]}
            </div>

            <p className="text-slate-600 leading-7">
              {item}
            </p>
          </div>
        ))}
      </div>

      <div className="
        mt-6
        rounded-2xl
        bg-gradient-to-r
        from-cyan-600
        to-teal-600
        p-5
        text-white
      ">
        <h3 className="font-semibold text-lg">
          AI Risk Assessment
        </h3>

        <p className="mt-2 text-cyan-100">
          Air quality is expected to remain stable over the next
          6 hours. Sensitive groups should consider limiting
          prolonged outdoor activities.
        </p>
      </div>
    </Card>
  );
}

export default AIRecommendations;