import Card from "../ui/Card";
import { Clock3, MapPin } from "lucide-react";
import { recentPredictions } from "../../data/dashboardData";

function RecentPredictions() {
  return (
    <Card className="h-full">
      <div className="mb-6">
        <h2 className="text-xl font-semibold">
          Recent Predictions
        </h2>
        <p className="text-sm text-slate-500">
          Latest AQI predictions generated by the AI model.
        </p>
      </div>

      <div className="space-y-4">
        {recentPredictions.map((prediction, index) => (
          <div
            key={index}
            className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 transition-all duration-300 hover:border-cyan-400 hover:shadow-md"
          >
            <div>
              <div className="flex items-center gap-2">
                <MapPin size={16} className="text-cyan-600" />
                <span className="font-semibold">
                  {prediction.city}
                </span>
              </div>

              <div className="mt-2 flex items-center gap-2 text-sm text-slate-500">
                <Clock3 size={14} />
                {prediction.time}
              </div>
            </div>

            <div className="text-right">
              <div className="text-3xl font-bold text-cyan-600">
                {prediction.aqi}
              </div>

              <div className="mt-1 rounded-full bg-cyan-100 px-3 py-1 text-xs font-medium text-cyan-700">
                {prediction.category}
              </div>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}

export default RecentPredictions;